version: "3"
services:
  xuanspa-app:
    build: .
    ports:
      - 5050:5050
    environment:
      MONGODB_CONNECTION_STRING: "${MONGODB_CONNECTION_STRING}"
      AZURE_CONNECTION_STRING: "${AZURE_CONNECTION_STRING}"
      AZURE_STORAGE_ACCOUNT_NAME: "${AZURE_STORAGE_ACCOUNT_NAME}"
      AZURE_STORAGE_ACCOUNT_ACCESS_KEY: "${AZURE_STORAGE_ACCOUNT_ACCESS_KEY}"
    restart: always
    volumes:
      - .:/home/app
      - /home/app/node_modules

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: testUser
      MONGO_INITDB_ROOT_PASSWORD: Toan1234

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: testUser
      ME_CONFIG_MONGODB_ADMINPASSWORD: Toan1234
      ME_CONFIG_MONGODB_URL: mongodb://testUser:Toan1234@mongo:27017/