apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xuanspa-pvc
  namespace: old-project
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-rwo